### ISSUE TITLE
ValueError: In MultiRNNCell, the input size of each next cell must match the output size of the previous one. Mismatched output size in cell 0.

### ISSUE THREAD

**Issue by NeymarL** [mouradmourafiq/tensorflow-lstm-regression#1]
I got the error when execute these lines:
```
X, y = generate_data(np.sin, np.linspace(0, 100, 10000), TIMESTEPS, seperate=False)
# create a lstm instance and validation monitor
validation_monitor = skflow.monitors.ValidationMonitor(X['val'], y['val'], n_classes=0,
                                                       print_steps=PRINT_STEPS,
                                                       early_stopping_rounds=1000)
regressor.fit(X['train'], y['train'], validation_monitor, logdir=LOG_DIR)
```

I didn't alter any variables, do you know how to fix it?
Thank you.

**Comment by mouradmourafiq** [comment]
I think you are using TensorFlow version 0.6.0 or r0.7. Can you please check? Otherwise can you tell me what os?

**Comment by dkarmon** [comment]
Same problem here.
I'm using version 0.8.0rc0, OSX.

Please advise
Thanks

**Comment by mouradmourafiq** [comment]
Ok I am also using OSX.

Can you execute this code instead:

```python
LOG_DIR = './ops_logs'
TIMESTEPS = 30
RNN_LAYERS = [{'steps': TIMESTEPS}]
DENSE_LAYERS = None
TRAINING_STEPS = 10000
BATCH_SIZE = 100
PRINT_STEPS = TRAINING_STEPS / 100

regressor = learn.TensorFlowEstimator(model_fn=lstm_model(TIMESTEPS, RNN_LAYERS, DENSE_LAYERS), n_classes=0,
                                      verbose=1,  steps=TRAINING_STEPS, optimizer='Adagrad',
                                      learning_rate=0.03, batch_size=BATCH_SIZE)

X, y = generate_data(np.sin, np.linspace(0, 100, 10000), TIMESTEPS, seperate=False)
# create a lstm instance and validation monitor
validation_monitor = learn.monitors.ValidationMonitor(X['val'], y['val'], n_classes=0,
                                                      print_steps=PRINT_STEPS,
                                                      early_stopping_rounds=1000)
regressor.fit(X['train'], y['train'], validation_monitor, logdir=LOG_DIR)
```
If this works, then the problem is that all layers must have the same size, i.e `RNN_LAYERS = [{'steps': TIMESTEPS}, {'steps': TIMESTEPS}]` if you need 2 layers. But I couldn't find the exception in the code.

Can you share the whole stack trace?

**Comment by dkarmon** [comment]
Still not working
`Using Theano backend.
Traceback (most recent call last):
  File "/Users/dk/Projects/plot_tf.py", line 123, in <module>
    regressor.fit(X['train'], y['train'], validation_monitor, logdir=LOG_DIR)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 254, in fit
    feed_params_fn=self._data_feeder.get_feed_params)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/trainer.py", line 59, in train
    feed_params_fn, loss_expression_tensor=loss)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 87, in update
    self._set_last_loss_seen()
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 173, in _set_last_loss_seen
    [val_loss] = self.sess.run([self.loss_expression_tensor], feed_dict=self.val_dict)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 553, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0, 1) for Tensor u'input:0', which has shape '(?, 30, 1)'
`

**Comment by mouradmourafiq** [comment]
it seems that it's not the same exception anymore, this one is related to the monitor. 

The thing is the code in the `learn` folder changes frequently, and since it's not the official interface, there's no deprecation process. The code runs on my machine with the latest tensorflow code.

One last thing that you can try is to execute the code without the validation monitor, i.e. `regressor.fit(X['train'], y['train'], logdir=LOG_DIR)` and see if it runs.

**Comment by dkarmon** [comment]
Now it works - executed the code without validation monitor.

**Comment by mouradmourafiq** [comment]
By the way there's a v0.8.0 available that you can install, you are still running on the v0.8.0rc version.

**Comment by dkarmon** [comment]
Updated already.
Can you please explain what is the problem with the validation monitor?

**Comment by mouradmourafiq** [comment]
I have no idea to be honest, and it's also hard to track the error unless you provide me with the last commit hash used in the version you are using and we can then check the code. But I am sure that the monitor class has changed a lot.

One thing you can also do to see if the problem is coming from my code or the library itself is to run this [example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/iris_val_based_early_stopping.py)

**Comment by dkarmon** [comment]
I ran the example and it seems that the library caused the error and not your code.

```
Traceback (most recent call last):
  File "/Users/dk/Projects/iris_test.py", line 44, in <module>
    classifier2.fit(X_train, y_train, val_monitor, logdir='/tmp/iris_model_val/')
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 254, in fit
    feed_params_fn=self._data_feeder.get_feed_params)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/trainer.py", line 59, in train
    feed_params_fn, loss_expression_tensor=loss)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 87, in update
    self._set_last_loss_seen()
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 173, in _set_last_loss_seen
    [val_loss] = self.sess.run([self.loss_expression_tensor], feed_dict=self.val_dict)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 553, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (23,) for Tensor u'output:0', which has shape '(?, 3)'
```

**Comment by mouradmourafiq** [comment]
So 2 options, either you won't be able to use this validation monitors or you can get the latest stable version of tensorflow. I also guess the second option would fix the original exception.
