### ISSUE TITLE
Update example to TF v0.11.0rc0 

### ISSUE THREAD

**Issue by claytantor** [mouradmourafiq/tensorflow-lstm-regression#12]
There were changes in TF v0.11.0rc0 that cause this example not to work, you could make a tag against master for v10 so it would still work for people using that version.

https://github.com/tensorflow/tensorflow/tree/v0.11.0rc0

FYI this is an important example. It is my belief it should be included in the tensorflow examples so it can be maintained.

**Comment by mouradmourafiq** [comment]
Hi @claytantor, thanks for letting me know, and sorry for the late response. I will try this weekend to update the code to be compatible with latest version.

**Comment by claytantor** [comment]
Just submitted a pr.
