### ISSUE TITLE
Update DNN to contrib.layers.???

### ISSUE THREAD

**Issue by alexshires** [mouradmourafiq/tensorflow-lstm-regression#14]
Hi,

Thanks for the awesome examples! They've been really helpful - however, when running the default setup out of the box, I have two comments.

Firstly, one needs to add pymongo to the list of packages. 

Secondly, the logistic regression part of the `_lstm_model` function fails in all the notebooks with 

```
/Users/ashires/tensorflow-lstm-regression/lstm.py in _lstm_model(X, y)
    114         #output = dnn_layers(output[-1], dense_layers)
    115         print type(output), output
--> 116         prediction, loss = learn.models.logistic_regression(output, y)
    117         train_op = tf.contrib.layers.optimize_loss(
    118             loss, tf.contrib.framework.get_global_step(), optimizer=optimizer,

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/models.pyc in logistic_regression(x, y, class_weight, init_mean, init_stddev)
    142     logging_ops.histogram_summary('%s.x' % scope_name, x)
    143     logging_ops.histogram_summary('%s.y' % scope_name, y)
--> 144     dtype = x.dtype.base_dtype
    145     # Set up the requested initialization.
    146     if init_mean is None:

AttributeError: 'list' object has no attribute 'dtype'
```

The documentation suggests one should pass a tensor?

**Comment by alexshires** [comment]
scrap that, I'd done something silly. I'm trying up update the `contrib.learn.ops.dnn` to `contrib.layers.stack` somehow though:

https://github.com/tensorflow/tensorflow/pull/2893/files

**Comment by alexshires** [comment]
should be part of #12

**Comment by kskalski** [comment]
With 0.11rc2 it actually fails now:
`return learn.ops.dnn(input_layers, layers)`
`AttributeError: 'module' object has no attribute 'dnn'`
It's not clear to me how `contrib.learn.ops.dnn` should be converted to `contrib.layers.stack`, I guess it might require some refactoring or maybe just using `contrib.layers.legacy_fully_connected` together with `contrib.layers.stack` properly

**Comment by mouradmourafiq** [comment]
The example has been updated to tf 0.11.0.

**Comment by alexshires** [comment]
thanks :)
