### ISSUE TITLE
learn.ops.dnn not found in a new TF version

### ISSUE THREAD

**Issue by luckyeu** [mouradmourafiq/tensorflow-lstm-regression#16]
I noticed, dnn function was removed from tensorflow.contrib.learn.ops location. 
You use it in lstm.py file and i got the next errors:
 
```
  File "/home/eugeny/Programming/TensorFlow/tensorflow-lstm-regression/lstm.py", line 114, in _lstm_model
    output = dnn_layers(output[-1], dense_layers)
  File "/home/eugeny/Programming/TensorFlow/tensorflow-lstm-regression/lstm.py", line 106, in dnn_layers
    return learn.ops.dnn(input_layers, layers)
AttributeError: module 'tensorflow.contrib.learn.python.learn.ops' has no attribute 'dnn'
```

What should i use instead of it? Help me out please.

**Comment by mouradmourafiq** [comment]
You are using the a new version of Tensorflow, the current code runs with TF 10, there's already a ticket to update the code to support the new api.

2 options, either you follow the [install requirements](https://github.com/mouradmourafiq/tensorflow-lstm-regression#install-requirements) step, or you can update the code to be compatible with the new TF version.

This ticket is related to #12
