### ISSUE TITLE
when i use input X as a vector,it can't work

### ISSUE THREAD

**Issue by Simon-Liu622** [mouradmourafiq/tensorflow-lstm-regression#2]
it seems that X can only a list of int or float,but can't be a list of a list,like this X = [[1,2,3],[4,5,6]].
So how can i fix it?
thanks a lot!

**Comment by mouradmourafiq** [comment]
Hi, it should be something like this:
```python
X = np.array([[[1], [2], [3]], [[4], [5], [6]]], dtype=float)
y = np.array([1, 2], dtype=float)
```
