### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'generator' and 'float'

### ISSUE THREAD

**Issue by cookiegg** [mouradmourafiq/tensorflow-lstm-regression#22]
```
predicted = regressor.predict(X['test'])
rmse = np.sqrt(((predicted - y['test']) ** 2).mean(axis=0))
score = mean_squared_error(predicted, y['test'])
print ("MSE: %f" % score)
```
we get a error:
`TypeError:unsupported operand type(s) for -: 'generator' and 'float' `
and I find the type of "predicted" is generator.
how could I deal with this problem?

my tensorflow version "0.12.0"
thanks !

**Comment by KeyYD** [comment]
I got the same problem!

**Comment by zhuojimmy** [comment]
It's my solution. Add the following code after `predicted = regressor.predict(X['test'])`
`predictedArr = np.array(list(predicted))
predictedArr.shape = -1,1`
and use `predictedArr ` replace `predicted`

**Comment by cookiegg** [comment]
thanks, i solved it.

2017-02-28 14:52 GMT+08:00 zhuojimmy <notifications@github.com>:
