### ISSUE TITLE
How do I save the training model and the results?like this：regressor.save('./ops_logs/lstm_run.model') , thank you~

### ISSUE THREAD

**Issue by Robintjhb** [mouradmourafiq/tensorflow-lstm-regression#25]
How do I save the training model and the results?
So I can directly use the last training model, this can reduce the forecast of the calculation time.
like this：regressor.save('./ops_logs/lstm_run.model') ,how can I do that? thank you~

**Comment by mouradmourafiq** [comment]
The model should be save automatically to the directory you provide.
