### ISSUE TITLE
How to deal with multiple dimensional data?

### ISSUE THREAD

**Issue by elwinmt** [mouradmourafiq/tensorflow-lstm-regression#27]
lstm.py works fine with one dimensional data. Now I have multi-dimensional data, but my prediction output is still one dimensional. How could I change the setting of dnn_layers and linear_regression to handle this case?

**Comment by mouradmourafiq** [comment]
You can feed any multi dimensional tensor, you just need to specify one unit output in your regressions layer (the output).
