### ISSUE TITLE
default config - random seed

### ISSUE THREAD

**Issue by pupilloirene** [mouradmourafiq/tensorflow-lstm-regression#29]
Is it possible to change default config to impose a random seed in order to have the same result any time i run the code?

**Comment by mouradmourafiq** [comment]
Hi,

You can try to set the seed on the [run_config])(https://github.com/mouradmourafiq/tensorflow-lstm-regression/blob/master/polyaxon_experiement.py#L16): `tf_random_seed`.

Let me know if it works.

**Comment by pupilloirene** [comment]
I have just found a solution:
regressor = learn.SKCompat(learn.Estimator(
    model_fn=lstm_model(
        TIMESTEPS,
        RNN_LAYERS,
        DENSE_LAYERS
    ),
    model_dir=LOG_DIR, config=tf.contrib.learn.RunConfig(tf_random_seed=42)
))

**Comment by mouradmourafiq** [comment]
👍  I will close then the issue
