### ISSUE TITLE
Error on regression

### ISSUE THREAD

**Issue by ehsanasgari** [mouradmourafiq/tensorflow-lstm-regression#5]
Hi there,

Thank you for your interesting code. However, I get an error at this line:
regressor.fit(X['train'], y['train'], monitors=[validation_monitor], logdir=LOG_DIR)

TypeError: evaluate() got an unexpected keyword argument 'batch_size'

Do you have any idea?

**Comment by mouradmourafiq** [comment]
I think tensorflow code has changed, and so I need to adapt this code accordingly, also I am still using here the `learn.TensorFlowEstimator` which is now deprecated.

I assume that the code can run if you omit the monitors, but I am not sure, I need to check.

**Comment by ky-xt** [comment]
year, The code can indeed run when I omit the monitors.
