### ISSUE TITLE
Timesteps vs Units

### ISSUE THREAD

**Issue by exodaniel** [mouradmourafiq/tensorflow-lstm-regression#6]
in lstm.py, you create BasicLSTMCells with layer['steps'] as the first argument.
However, if I understand the tensorflow implementation correctly (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell.py#L179)
this argument (num_units in `BasicLSTMCell(num_units)`) refers to the number of units - i.e. memory cells in the LSTM cell.
 
 ``` python
   def lstm_cells(layers):
        if isinstance(layers[0], dict):
            return [tf.nn.rnn_cell.DropoutWrapper(tf.nn.rnn_cell.BasicLSTMCell(layer['steps'],
                                                                               state_is_tuple=True),
                                                  layer['keep_prob'])
                    if layer.get('keep_prob') else tf.nn.rnn_cell.BasicLSTMCell(layer['steps'],
                                                                                state_is_tuple=True)
                    for layer in layers]
        return [tf.nn.rnn_cell.BasicLSTMCell(steps, state_is_tuple=True) for steps in layers]

```

As a result, in your notebook the variable TIMESTEPS affects both the amount of timesteps used in truncated backpropagation through time, but also the size of the LSTM.

Is this voluntary?

**Comment by mouradmourafiq** [comment]
Yes it's voluntary, you can tweak the model if you need to introduce the truncated backpropagation. Truncating backpropagation is connected with the learning and not with the length of the sequence, and this parameter can't be bigger than length of the sequence.

I assume that this is a source of confusion to many people who tried my example, I will probably just add this option to the model when I have time.

**Comment by exodaniel** [comment]
All good, I'll close the issue then. I appreciate the explanation.

And by the way, great work on this project!
