### ISSUE TITLE
Type error at cell 4 on lstm_sin.ipynb

### ISSUE THREAD

**Issue by softgearko** [mouradmourafiq/tensorflow-lstm-regression#8]
Thank you for upgrading codes for tensorflow 0.10.0.

I got an error at cell 4 on lstm_sin.ipynb because of using float64.
So I just did workaround: adding dtype=np.float32 into np.linspace() such as:
`X, y = generate_data(np.sin, np.linspace(0, 100, 10000, dtype=np.float32 ), TIMESTEPS, seperate=False)`
I think, this modification can be adapted to other ipynb files in this project.

**Comment by mouradmourafiq** [comment]
Sorry for the late answer, the code was updated. 
Thank you for reporting this issue.
